# Generated by Django 6.1.1 on 2026-10-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=10),
        ),
    ]
