# Generated by Django 6.1.1 on 2026-10-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_users_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundrequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
